---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app
  namespace: argo-learning
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: "vinayakojha47/nodejsapp-1.0:latest"
        ports:
          - containerPort: 3000
