apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: argo-learning
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
  - name: http
    port: 80                 # Add this line to specify the port exposed by the service
    targetPort: 3000         # The port on the container to which traffic will be directed
    nodePort: 32007          # The port on the node to expose this service (for NodePort)

